pipeline{
    agent any

    stages{
        stage('Build'){
            agent{
                docker{
                    image 'maven:3.9.11-eclipse-temurin-11-alpine'
                    reuseNode true
                }
            }

            steps{
                dir('demo'){
                    sh 'mvn clean package'
                }
            }
        }

//         stage('Docker'){
//             steps{
//                 withCredentials([usernamePassword(credentialsId: "docker", passwordVariable: "docker_pass", usernameVariable: "docker_user")]){
//                     sh'''
//                         docker login -u $docker_user -p $docker_pass
//                         docker build -t $docker_user/task-manage .
//                         docker push $docker_user/task-manage:latest
//                     '''
//                 }
//             }
//         }

    }
}